services:
  - type: web
    name: shiptrack-pro-api
    runtime: docker
    rootDir: shiptrack-pro
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false